name: README Info Update

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    name: GitHub README Generator
    runs-on: ubuntu-latest
    steps:
      - uses: th3c0d3br34ker/github-readme-info@master
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          TIMEZONE: "Asia/Kolkata"
          SHOW_LINES_OF_CODE: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_DAILY_COMMIT: "False"
          SHOW_WEEKLY_COMMIT: "False"
          SHOW_LANGUAGE: "False"
          SHOW_TOTAL_CONTRIBUTIONS: "False"
          SAY_THANKS: "True"
